# Generated by Django 4.1.5 on 2023-01-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
